on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # this permission is mandatory for trusted publishing To PyPI
      id-token: write

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI using trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
